"""Seed the artists table with well-known artists from dice.fm directory."""
import asyncio
import os
import re
import uuid

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker

# Artists data: (name, genre)
ARTISTS = [
    # A
    ("A$AP Rocky", "Hip-Hop"),
    ("Adele", "Pop"),
    ("Aerosmith", "Rock"),
    ("Alanis Morissette", "Alternative"),
    ("Alesso", "Electronic"),
    ("Alice In Chains", "Rock"),
    ("Alt-J", "Indie"),
    ("Amaarae", "Afrobeats"),
    ("Amine", "Hip-Hop"),
    ("Anderson .Paak", "R&B"),
    ("Anitta", "Pop"),
    ("Aphex Twin", "Electronic"),
    ("Arcade Fire", "Indie"),
    ("Arctic Monkeys", "Rock"),
    ("Ariana Grande", "Pop"),
    ("Armand Van Helden", "House"),
    ("Arlo Parks", "Indie"),
    ("Art Blakey", "Jazz"),
    ("Ashnikko", "Pop"),
    ("Avenged Sevenfold", "Metal"),
    ("Axwell", "House"),
    # B
    ("Babymetal", "Metal"),
    ("Bad Bunny", "Reggaeton"),
    ("Bastille", "Pop"),
    ("Bauhaus", "Post-Punk"),
    ("Beach House", "Dream Pop"),
    ("Beabadoobee", "Indie"),
    ("Becky Hill", "Dance"),
    ("Beyonce", "Pop"),
    ("Bicep", "Electronic"),
    ("Billie Eilish", "Pop"),
    ("Bjork", "Art Pop"),
    ("Black Coffee", "House"),
    ("Black Sabbath", "Metal"),
    ("Bladee", "Hip-Hop"),
    ("Blondie", "New Wave"),
    ("Blur", "Britpop"),
    ("Bob Dylan", "Folk"),
    ("Bob Marley", "Reggae"),
    ("Bonobo", "Electronic"),
    ("Boris Brejcha", "Techno"),
    ("Boy Harsher", "Darkwave"),
    ("Bring Me The Horizon", "Rock"),
    ("Bruce Springsteen", "Rock"),
    ("Burial", "Electronic"),
    ("Burna Boy", "Afrobeats"),
    # C
    ("Cardi B", "Hip-Hop"),
    ("Carl Cox", "Techno"),
    ("Caroline Polacheck", "Pop"),
    ("Cat Stevens", "Folk"),
    ("Central Cee", "Hip-Hop"),
    ("Charli XCX", "Pop"),
    ("Charlotte De Witte", "Techno"),
    ("Chase & Status", "Drum & Bass"),
    ("Chemical Brothers", "Electronic"),
    ("Childish Gambino", "Hip-Hop"),
    ("Chris Stapleton", "Country"),
    ("Christine and the Queens", "Pop"),
    ("Clairo", "Indie"),
    ("Claptone", "House"),
    ("Coldplay", "Pop"),
    ("Confidence Man", "Electronic"),
    ("Corbin", "Alternative"),
    ("Cosmo Pyke", "Indie"),
    ("CRJ (Carly Rae Jepsen)", "Pop"),
    # D
    ("D-Block Europe", "Hip-Hop"),
    ("Daft Punk", "Electronic"),
    ("Damian Lazarus", "House"),
    ("Daniel Avery", "Electronic"),
    ("Daniel Caesar", "R&B"),
    ("Daughter", "Indie"),
    ("Dave", "Hip-Hop"),
    ("David Bowie", "Rock"),
    ("David Guetta", "EDM"),
    ("Deadmau5", "Electronic"),
    ("Death Grips", "Experimental"),
    ("Depeche Mode", "Synth-Pop"),
    ("Desiigner", "Hip-Hop"),
    ("Destiny's Child", "R&B"),
    ("Diplo", "Electronic"),
    ("Disclosure", "House"),
    ("DJ Shadow", "Electronic"),
    ("Doja Cat", "Pop"),
    ("Dominic Fike", "Indie"),
    ("Drake", "Hip-Hop"),
    ("Dua Lipa", "Pop"),
    ("Dubfire", "Techno"),
    # E
    ("Earl Sweatshirt", "Hip-Hop"),
    ("Ed Sheeran", "Pop"),
    ("Elbow", "Indie"),
    ("Elastica", "Britpop"),
    ("Electric Wizard", "Metal"),
    ("Elton John", "Pop"),
    ("Eminem", "Hip-Hop"),
    ("Empire of the Sun", "Electronic"),
    ("Erykah Badu", "R&B"),
    ("Everything Everything", "Indie"),
    # F
    ("Faith No More", "Rock"),
    ("Fat Freddy's Drop", "Dub"),
    ("Fatboy Slim", "Electronic"),
    ("Faye Webster", "Indie"),
    ("FKA Twigs", "Art Pop"),
    ("Fleetwood Mac", "Rock"),
    ("Florence + The Machine", "Indie"),
    ("Flying Lotus", "Electronic"),
    ("Fontaines D.C.", "Post-Punk"),
    ("Foo Fighters", "Rock"),
    ("Four Tet", "Electronic"),
    ("Frank Ocean", "R&B"),
    ("Fred Again..", "Electronic"),
    ("Freddie Gibbs", "Hip-Hop"),
    ("Future", "Hip-Hop"),
    # G
    ("Gerry Cinnamon", "Folk"),
    ("Glass Animals", "Indie"),
    ("Gorillaz", "Alternative"),
    ("Green Day", "Punk"),
    ("Grimes", "Electronic"),
    ("Griz", "Electronic"),
    ("Gunna", "Hip-Hop"),
    # H
    ("H.E.R.", "R&B"),
    ("Halsey", "Pop"),
    ("Harry Styles", "Pop"),
    ("Headie One", "Hip-Hop"),
    ("Helena Hauff", "Techno"),
    ("Herbie Hancock", "Jazz"),
    ("Honey Dijon", "House"),
    ("Hot Chip", "Electronic"),
    ("Hozier", "Folk"),
    # I
    ("Ice Spice", "Hip-Hop"),
    ("Iggy Pop", "Rock"),
    ("Inhaler", "Rock"),
    ("Iron Maiden", "Metal"),
    ("Idles", "Post-Punk"),
    # J
    ("J Balvin", "Reggaeton"),
    ("J. Cole", "Hip-Hop"),
    ("J Hus", "Hip-Hop"),
    ("Jack Harlow", "Hip-Hop"),
    ("Jack Johnson", "Folk"),
    ("Jack White", "Rock"),
    ("Jamie xx", "Electronic"),
    ("James Blake", "Electronic"),
    ("Janelle Monae", "R&B"),
    ("Jay-Z", "Hip-Hop"),
    ("Jessie Ware", "Pop"),
    ("Jhene Aiko", "R&B"),
    ("Jimi Hendrix", "Rock"),
    ("Jorja Smith", "R&B"),
    ("Joy Division", "Post-Punk"),
    ("Juice WRLD", "Hip-Hop"),
    ("Jungle", "Electronic"),
    ("Justin Bieber", "Pop"),
    # K
    ("Kali Uchis", "R&B"),
    ("Kanye West", "Hip-Hop"),
    ("Kaytranada", "Electronic"),
    ("Keane", "Indie"),
    ("Kendrick Lamar", "Hip-Hop"),
    ("Kenny Beats", "Hip-Hop"),
    ("Kerri Chandler", "House"),
    ("Kevin Abstract", "Hip-Hop"),
    ("Khruangbin", "Psychedelic"),
    ("Kim Petras", "Pop"),
    ("King Gizzard & The Lizard Wizard", "Psychedelic"),
    ("King Krule", "Indie"),
    ("Knucks", "Hip-Hop"),
    ("Koffee", "Reggae"),
    # L
    ("LCD Soundsystem", "Electronic"),
    ("Lady Gaga", "Pop"),
    ("Lana Del Rey", "Pop"),
    ("Larry Heard", "House"),
    ("Lewis Capaldi", "Pop"),
    ("Lianne La Havas", "R&B"),
    ("Lil Nas X", "Hip-Hop"),
    ("Lil Uzi Vert", "Hip-Hop"),
    ("Lil Wayne", "Hip-Hop"),
    ("Lizzo", "Pop"),
    ("Logic", "Hip-Hop"),
    ("London Grammar", "Indie"),
    ("Loyle Carner", "Hip-Hop"),
    # M
    ("Mac DeMarco", "Indie"),
    ("Macklemore", "Hip-Hop"),
    ("Madlib", "Hip-Hop"),
    ("Madonna", "Pop"),
    ("Maggie Rogers", "Indie"),
    ("Maisie Peters", "Pop"),
    ("Major Lazer", "Electronic"),
    ("Maneskin", "Rock"),
    ("Massive Attack", "Trip-Hop"),
    ("Megan Thee Stallion", "Hip-Hop"),
    ("Metro Boomin", "Hip-Hop"),
    ("Metronomy", "Electronic"),
    ("MGMT", "Indie"),
    ("Michael Kiwanuka", "Soul"),
    ("Miguel", "R&B"),
    ("Miley Cyrus", "Pop"),
    ("MJ Cole", "Garage"),
    ("Moderat", "Electronic"),
    ("Mura Masa", "Electronic"),
    ("Muse", "Rock"),
    # N
    ("Nao", "R&B"),
    ("Nas", "Hip-Hop"),
    ("Nelly Furtado", "Pop"),
    ("New Order", "Synth-Pop"),
    ("Nick Cave", "Rock"),
    ("Nicki Minaj", "Hip-Hop"),
    ("Nina Kraviz", "Techno"),
    ("Nirvana", "Grunge"),
    ("Noel Gallagher", "Rock"),
    ("Nothing But Thieves", "Rock"),
    ("Noname", "Hip-Hop"),
    # O
    ("Oasis", "Britpop"),
    ("Octavian", "Hip-Hop"),
    ("Offset", "Hip-Hop"),
    ("Olivia Dean", "R&B"),
    ("Olivia Rodrigo", "Pop"),
    ("Omar Apollo", "R&B"),
    # P
    ("Panda Bear", "Electronic"),
    ("Panic! At The Disco", "Rock"),
    ("Paramore", "Rock"),
    ("Peggy Gou", "House"),
    ("Pharrell Williams", "Hip-Hop"),
    ("Phoebe Bridgers", "Indie"),
    ("Pink Floyd", "Rock"),
    ("PinkPantheress", "Pop"),
    ("Playboi Carti", "Hip-Hop"),
    ("Post Malone", "Pop"),
    ("Prince", "Funk"),
    ("Primal Scream", "Rock"),
    ("Pusha T", "Hip-Hop"),
    # Q
    ("Queen", "Rock"),
    ("Questlove", "Hip-Hop"),
    ("Quincy Jones", "Jazz"),
    # R
    ("Radiohead", "Alternative"),
    ("Rae Sremmurd", "Hip-Hop"),
    ("Raye", "R&B"),
    ("Rema", "Afrobeats"),
    ("Rihanna", "Pop"),
    ("Rina Sawayama", "Pop"),
    ("Robyn", "Pop"),
    ("Roddy Ricch", "Hip-Hop"),
    ("Rosalia", "Pop"),
    ("Romy", "Electronic"),
    ("Run The Jewels", "Hip-Hop"),
    # S
    ("Sabrina Carpenter", "Pop"),
    ("Sam Fender", "Rock"),
    ("Sam Smith", "Pop"),
    ("Sampa The Great", "Hip-Hop"),
    ("Sault", "R&B"),
    ("Schoolboy Q", "Hip-Hop"),
    ("Self Esteem", "Pop"),
    ("Sephira", "Electronic"),
    ("Shygirl", "Electronic"),
    ("Sigrid", "Pop"),
    ("SL", "Hip-Hop"),
    ("Skepta", "Grime"),
    ("Skrillex", "Electronic"),
    ("Slowdive", "Shoegaze"),
    ("Slowthai", "Hip-Hop"),
    ("Snoh Aalegra", "R&B"),
    ("Solange", "R&B"),
    ("Sonny Fodera", "House"),
    ("SOS", "Pop"),
    ("Stefflon Don", "Hip-Hop"),
    ("Stormzy", "Grime"),
    ("Sugababes", "Pop"),
    ("SZA", "R&B"),
    # T
    ("Tame Impala", "Psychedelic"),
    ("Taylor Swift", "Pop"),
    ("Tchami", "House"),
    ("Tears For Fears", "Synth-Pop"),
    ("Tennyson", "Electronic"),
    ("The 1975", "Pop"),
    ("The Beatles", "Rock"),
    ("The Black Keys", "Rock"),
    ("The Blaze", "Electronic"),
    ("The Cure", "Post-Punk"),
    ("The Interrupters", "Ska"),
    ("The Killers", "Rock"),
    ("The National", "Indie"),
    ("The Rolling Stones", "Rock"),
    ("The Smile", "Rock"),
    ("The Strokes", "Rock"),
    ("The War On Drugs", "Indie"),
    ("The Weeknd", "R&B"),
    ("The XX", "Indie"),
    ("Thundercat", "Jazz"),
    ("Tiesto", "EDM"),
    ("Tinie Tempah", "Hip-Hop"),
    ("Tinashe", "R&B"),
    ("Tobe Nwigwe", "Hip-Hop"),
    ("Tom Misch", "Jazz"),
    ("Tones and I", "Pop"),
    ("Travis Scott", "Hip-Hop"),
    ("Turnstile", "Punk"),
    ("Twenty One Pilots", "Pop"),
    ("Tyler The Creator", "Hip-Hop"),
    # U
    ("UB40", "Reggae"),
    ("Underworld", "Electronic"),
    ("Unknown Mortal Orchestra", "Psychedelic"),
    # V
    ("Vampire Weekend", "Indie"),
    ("Vince Staples", "Hip-Hop"),
    # W
    ("Wet Leg", "Indie"),
    ("Willow", "Pop"),
    ("Wolf Alice", "Rock"),
    ("Wu-Tang Clan", "Hip-Hop"),
    # X
    ("XXXTentacion", "Hip-Hop"),
    # Y
    ("Yaeji", "Electronic"),
    ("Yeat", "Hip-Hop"),
    ("Young Thug", "Hip-Hop"),
    ("Yung Lean", "Hip-Hop"),
    # Z
    ("Zara Larsson", "Pop"),
    ("Zedd", "EDM"),
    # Additional well-known artists from dice.fm
    ("070 Shake", "Hip-Hop"),
    ("100 gecs", "Hyperpop"),
    ("21 Savage", "Hip-Hop"),
    ("2Pac", "Hip-Hop"),
    ("50 Cent", "Hip-Hop"),
    ("6LACK", "R&B"),
    ("A Boogie Wit da Hoodie", "Hip-Hop"),
    ("Abel Selaocoe", "Jazz"),
    ("Above & Beyond", "Trance"),
    ("Acid Arab", "Electronic"),
    ("Action Bronson", "Hip-Hop"),
    ("Adam Beyer", "Techno"),
    ("Adrianne Lenker", "Folk"),
    ("AG Club", "Hip-Hop"),
    ("Aitch", "Hip-Hop"),
    ("Alabama Shakes", "Rock"),
    ("Alex G", "Indie"),
    ("Alice Phoebe Lou", "Folk"),
    ("Amadou & Mariam", "World"),
    ("Amyl and The Sniffers", "Punk"),
    ("Angel Olsen", "Indie"),
    ("Arlo Parks", "Indie"),
    ("Ashnikko", "Pop"),
    ("Autechre", "Electronic"),
    ("Avalanches", "Electronic"),
    ("Badbadnotgood", "Jazz"),
    ("Bakar", "Indie"),
    ("Bambii", "Electronic"),
    ("Banks", "R&B"),
    ("Bartees Strange", "Indie"),
    ("Beach Bunny", "Indie"),
    ("Benee", "Pop"),
    ("Benjamin Clementine", "Art Pop"),
    ("Big Thief", "Indie"),
    ("Billy Nomates", "Post-Punk"),
    ("Black Country New Road", "Post-Rock"),
    ("Black Midi", "Experimental"),
    ("Blood Orange", "R&B"),
    ("Bon Iver", "Indie"),
    ("Brockhampton", "Hip-Hop"),
    ("Cate Le Bon", "Indie"),
    ("Celeste", "R&B"),
    ("Channel Tres", "House"),
    ("Chet Faker", "Electronic"),
    ("CHVRCHES", "Synth-Pop"),
    ("Cigarettes After Sex", "Dream Pop"),
    ("City Girls", "Hip-Hop"),
    ("Conan Gray", "Pop"),
    ("Conway the Machine", "Hip-Hop"),
    ("Corto.alto", "Jazz"),
    ("Cory Henry", "Jazz"),
    ("Courtney Barnett", "Indie"),
    ("Crack Cloud", "Post-Punk"),
    ("Cuco", "Indie"),
    ("D Double E", "Grime"),
    ("Danny Brown", "Hip-Hop"),
    ("Dave Clarke", "Techno"),
    ("Dawn Richard", "R&B"),
    ("Denzel Curry", "Hip-Hop"),
    ("Dermot Kennedy", "Folk"),
    ("Diana Ross", "Soul"),
    ("Dinner Party", "Jazz"),
    ("DJ EZ", "Garage"),
    ("DJ Koze", "House"),
    ("DJ Premier", "Hip-Hop"),
    ("Doechii", "Hip-Hop"),
    ("Dry Cleaning", "Post-Punk"),
    ("Duran Duran", "New Wave"),
    ("EARTHGANG", "Hip-Hop"),
    ("Easy Life", "Indie"),
    ("Elderbrook", "Electronic"),
    ("Ella Mai", "R&B"),
    ("Eliza Rose", "House"),
    ("Ezra Collective", "Jazz"),
    ("Floating Points", "Electronic"),
    ("Flume", "Electronic"),
    ("Frank Turner", "Folk"),
    ("Freddie Mercury", "Rock"),
    ("Gabriels", "R&B"),
    ("Gang of Youths", "Rock"),
    ("George Ezra", "Pop"),
    ("Ghost", "Metal"),
    ("Giggs", "Hip-Hop"),
    ("Gilla Band", "Noise Rock"),
    ("Girl In Red", "Indie"),
    ("Goldlink", "Hip-Hop"),
    ("Grace Jones", "Pop"),
    ("Greentea Peng", "R&B"),
    ("Griselda", "Hip-Hop"),
    ("Grizzly Bear", "Indie"),
    ("Haim", "Rock"),
    ("Hans Zimmer", "Classical"),
    ("Headie One", "Hip-Hop"),
    ("Holly Humberstone", "Pop"),
    ("Hope Tala", "R&B"),
    ("IDER", "Indie"),
    ("Injury Reserve", "Hip-Hop"),
    ("Jai Paul", "Electronic"),
    ("James Hype", "House"),
    ("Japanese Breakfast", "Indie"),
    ("Jayda G", "House"),
    ("JID", "Hip-Hop"),
    ("Jockstrap", "Electronic"),
    ("John Summit", "House"),
    ("Jon Hopkins", "Electronic"),
    ("Jorja Smith", "R&B"),
    ("Joy Crookes", "R&B"),
    ("Kamasi Washington", "Jazz"),
    ("Karate", "Indie"),
    ("Kehlani", "R&B"),
    ("Kelly Lee Owens", "Electronic"),
    ("Kelela", "R&B"),
    ("Kenny Dixon Jr", "House"),
    ("Kojey Radical", "Hip-Hop"),
    ("Kokoroko", "Jazz"),
    ("JPEGMAFIA", "Hip-Hop"),
    ("Kurt Vile", "Indie"),
    ("La Femme", "French Pop"),
    ("Lana Del Rey", "Pop"),
    ("Lane 8", "Electronic"),
    ("Laura Marling", "Folk"),
    ("Lauryn Hill", "Hip-Hop"),
    ("Leon Bridges", "Soul"),
    ("Leon Vynehall", "Electronic"),
    ("Lettuce", "Funk"),
    ("Liam Gallagher", "Rock"),
    ("Little Dragon", "Electronic"),
    ("Little Simz", "Hip-Hop"),
    ("Loraine James", "Electronic"),
    ("Lucky Daye", "R&B"),
    ("Mahalia", "R&B"),
    ("Mall Grab", "House"),
    ("Mansur Brown", "Jazz"),
    ("Maple Glider", "Folk"),
    ("Masego", "R&B"),
    ("Matt Corby", "Indie"),
    ("Maya Jane Coles", "House"),
    ("Megan Thee Stallion", "Hip-Hop"),
    ("Mereba", "R&B"),
    ("Michael Bibi", "House"),
    ("Mitski", "Indie"),
    ("Moses Boyd", "Jazz"),
    ("Moses Sumney", "Art Pop"),
    ("Mount Kimbie", "Electronic"),
    ("Nao", "R&B"),
    ("Natasha Bedingfield", "Pop"),
    ("Nathy Peluso", "Latin"),
    ("Nines", "Hip-Hop"),
    ("ENNY", "Hip-Hop"),
    ("Novelist", "Grime"),
    ("Nubya Garcia", "Jazz"),
    ("Obongjayar", "R&B"),
    ("Overmono", "Electronic"),
    ("Pa Salieu", "Hip-Hop"),
    ("Partiboi69", "Electronic"),
    ("Polo G", "Hip-Hop"),
    ("Pop Smoke", "Hip-Hop"),
    ("Porridge Radio", "Indie"),
    ("Priya Ragu", "Pop"),
    ("Raveena", "R&B"),
    ("Rex Orange County", "Indie"),
    ("Richie Hawtin", "Techno"),
    ("Rico Nasty", "Hip-Hop"),
    ("Robert Glasper", "Jazz"),
    ("Roisin Murphy", "Electronic"),
    ("Ross From Friends", "Electronic"),
    ("Rufus Du Sol", "Electronic"),
    ("Sampha", "Electronic"),
    ("Sasha", "Electronic"),
    ("Shabaka", "Jazz"),
    ("Sheck Wes", "Hip-Hop"),
    ("Sherelle", "Electronic"),
    ("Show Me The Body", "Punk"),
    ("Soccer Mommy", "Indie"),
    ("Solomun", "House"),
    ("Sons of Kemet", "Jazz"),
    ("Squid", "Post-Punk"),
    ("Steve Lacy", "R&B"),
    ("Still Woozy", "Indie"),
    ("Sudan Archives", "R&B"),
    ("Summer Walker", "R&B"),
    ("Tems", "R&B"),
    ("Tion Wayne", "Hip-Hop"),
    ("Tkay Maidza", "Hip-Hop"),
    ("TNGHT", "Electronic"),
    ("Toro Y Moi", "Indie"),
    ("Vegyn", "Electronic"),
    ("Victoria Monet", "R&B"),
    ("Vulfpeck", "Funk"),
    ("Wizkid", "Afrobeats"),
    ("Yung Bleu", "R&B"),
    ("Yves Tumor", "Experimental"),
    ("Zelooperz", "Hip-Hop"),
]


def slugify(name: str) -> str:
    s = name.lower().strip()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"-+", "-", s)
    return s.strip("-")


async def main():
    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        print("DATABASE_URL not set")
        return

    if db_url.startswith("postgresql://"):
        db_url = db_url.replace("postgresql://", "postgresql+asyncpg://", 1)

    engine = create_async_engine(db_url)

    async with engine.begin() as conn:
        # Create table if not exists
        await conn.execute(text("""
            CREATE TABLE IF NOT EXISTS artists (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                name VARCHAR(255) NOT NULL,
                slug VARCHAR(255) NOT NULL UNIQUE,
                image_url TEXT,
                genre VARCHAR(100),
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            )
        """))
        await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_artists_name ON artists (name)"))
        await conn.execute(text("CREATE INDEX IF NOT EXISTS ix_artists_slug ON artists (slug)"))

    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    created = 0
    skipped = 0
    seen_slugs = set()

    async with async_session() as session:
        for name, genre in ARTISTS:
            slug = slugify(name)
            if not slug or slug in seen_slugs:
                skipped += 1
                continue
            seen_slugs.add(slug)

            result = await session.execute(
                text("SELECT id FROM artists WHERE slug = :slug"), {"slug": slug}
            )
            if result.scalar_one_or_none():
                skipped += 1
                continue

            await session.execute(
                text("""
                    INSERT INTO artists (id, name, slug, genre)
                    VALUES (:id, :name, :slug, :genre)
                """),
                {"id": str(uuid.uuid4()), "name": name, "slug": slug, "genre": genre},
            )
            created += 1

        await session.commit()

    await engine.dispose()
    print(f"Done! Created {created}, skipped {skipped} (total entries: {len(ARTISTS)})")


if __name__ == "__main__":
    asyncio.run(main())
